add question
jpreprocess/jlabel pull request #3
Opened 2024-01-14 14:09 UTC by cm-ayf

2024-01-14 14:15 UTC, cm-ayf commented
coverage……

2024-01-14 14:16 UTC, cm-ayf commented
供養
<details>

# パターンの構造

- パターンは3つの部分に分かれる：
  - 「数字」より前
  - 「数字」
  - 「数字」より後
- ここで，「数字」はPhoneを含む
- 「数字」より前と「数字」より後は，「見るべき場所」を示している
  - 「見るべき場所」が最初か最後の場合，それぞれ「数字」より前と「数字」より後は空
- 「数字」より前と「数字」より後は，区切り文字と`*`で区切られている
  - 区切り文字：`/A:`…`/K:`，`-`，`+`，`_`，`!`，`#`，`@`，`|`，`%`，`@`，`+`，`&`
- 「数字」は，許される値の「範囲」を示している
  - ただし「範囲」はRangeまたは許される「数字」の集合のいずれか
- 「数字」は，`?`を含む場合と含まない場合がある
  - `?`を含む場合：`?`，`??`，`1?`…`9?`のいずれか
  - `?`を含まない場合：`0`…`9`，`00`…`09`，`10`…`99`のいずれか

# 質問の構造

- 質問は，名前と，パターンの集合からなる
- 名前は，しばしば`=`や`<=`と数字で終わっているが，その限りではない
- パターンの集合は，すべて同じ見るべき場所を指している

# 「見るべき場所」の一覧

```
LL-Phone      ,^*
L-Phone     *^,-*
C-Phone     *-,+*
R-Phone     *+,=*
RR-Phone    *=,/A:*

C-Mora_diff_Acc-Type       */A:,+*
C-Mora_Fw-Pos-in_Acc_Mora    *+,+*
C-Mora_Bw-Pos-in_Acc_Mora    *+,/B:*

L-Hinshi        */B:,-*
L-Katsuyougata    *-,_*
L-Katsuyoukei     *_,/C:*

C-Hinshi        */C:,_*
C-Katsuyougata    *_,+*
C-Katsuyoukei     *+,/D:*

R-Hinshi        */D:,+*
R-Katsuyougata    *+,_*
R-Katsuyoukei     *_,/E:*

L-Acc_Len_Mora      */E:,_*
L-Acc-Type            *_,!*
L-Acc-Interrogative   *!,_*
(xx)                  *_,-*
L-Acc_Pau_C-Acc       *-,/F:*

C-Acc_Len_Mora          */F:,_*
C-Acc-Type                *_,#*
C-Acc-Interrogative       *#,_*
(xx)                      *_,@*
C-Acc_Fw-Pos-in_Br_Acc    *@,_*
C-Acc_Bw-Pos-in_Br_Acc    *_,|*
C-Acc_Fw-Pos-in_Br_Mora   *|,_*
C-Acc_Bw-Pos-in_Br_Mora   *_,/G:*

R-Acc_Len_Mora          */G:,_*
R-Acc-Type                *_,%*
R-Acc-Interrogative       *%,_*
(xx)                      *_,_*
C-Acc_Pau_R-Acc           *_,/H:*

L-Br_Len_Acc    */H:,_*
L-Br_Len_Mora     *_,/I:*

C-Br_Len_Acc            */I:,-*
C-Br_Len_Mora             *-,@*
C-Br_Fw-Pos-in_Utt_Br     *@,+*
C-Br_Bw-Pos-in_Utt_Br     *+,&*
C-Br_Fw-Pos-in_Utt_Acc    *&,-*
C-Br_Bw-Pos-in_Utt_Acc    *-,|*
C-Br_Fw-Pos-in_Utt_Mora   *|,+*
C-Br_Bw-Pos-in_Utt_Mora   *+,/J:*

R-Br_Len_Acc    */J:,_*
R-Br_Len_Mora     *_,/K:*

Utt_Len_Br    */K:,+*
Utt_Len_Acc     *+,-*
Utt_Len_Mora    *-,
```

# 質問をstructとenumで表す

- 質問は「見るべき場所」と「範囲」の組み合わせとなる
- 「見るべき場所」によって「範囲」の表し方が異なる
  - 音素部分は`[&str]`
  - `/A:`，`/E:`…`/K:`は`Range<i8>`
    - ただし負になりうるのは`/A:`の最初だけ
  - `/B:`…`/D:`は`[&i8]`

</details>

2024-01-15 09:24 UTC, femshima requested changes
テストの追加は難しいバグに当たるところまでやりましたが，カバレッジが足りないのでマージ前に追加します．
P.S. rebaseはしていないので，お願いします．

2024-01-15 09:24 UTC, femshima commented on src/question/position.rs
> +                            (from, to)
`-??`は-99から0ではなく，-99から-10という意味なので，`.max(10)`などが必要かと思われます．
（ゼロ埋めを行っているのはWordだけです）
ついでに：このフレーズが三回出てくるので，関数か何かに共通化したほうが良いと思います．

2024-01-15 09:56 UTC, femshima commented on src/question/position.rs
> +                            (from, to)
たとえばこんな感じですかね
```rs
pub fn parse_wildcard(range: &str) -> Option<Range<u8>> {
    debug_assert_eq!(range.chars().next(), Some('?'));
    let from = range
        .replacen('?', "1", 1)
        .replace('?', "0")
        .parse::<u8>()
        .ok()?;
    let to = range.replace('?', "9").parse::<u8>().ok()?;
    Some(from..to + 1)
}
```

2024-01-15 11:17 UTC, femshima commented on src/question/position.rs
> +                            (from, to)
逆でした．
```rs
use std::ops::Range;

pub fn parse_wildcard(range: &str) -> Option<Range<u16>> {
    debug_assert!(range.ends_with('?'));
    if range == "?" {
        return Some(0..10);
    }

    let prefix: String = range.chars().take_while(|c| *c != '?').collect();

    if range[prefix.len()..].chars().any(|c| c != '?') {
        return None;
    }

    let shifter = 10u16.pow((range.len() - prefix.len() - 1) as u32);
    if prefix.is_empty() {
        let from = shifter;
        let to = shifter * 10;
        Some(from..to)
    } else {
        let prefix_parsed = prefix.parse::<u16>().ok()?;
        let from = prefix_parsed * shifter * 10;
        let to = (prefix_parsed + 1) * shifter * 10;
        Some(from..to)
    }
}

#[test]
fn wildcard() {
    assert_eq!(parse_wildcard("?"), Some(0..10));
    assert_eq!(parse_wildcard("??"), Some(10..100));
    assert_eq!(parse_wildcard("???"), Some(100..1000));
    assert_eq!(parse_wildcard("?1?"), None);
    assert_eq!(parse_wildcard("1?"), Some(10..20));
    assert_eq!(parse_wildcard("1??"), Some(100..200));
}
```

2024-01-16 09:55 UTC, merged